# Generated by Django 5.0.6 on 2024-06-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='taken',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_cost',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('creationDate', models.DateTimeField()),
                ('expirationDate', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.client')),
            ],
        ),
    ]
