# Generated by Django 5.0.6 on 2024-06-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_reservation_taken_reservation_total_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('costPerNight', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='dressing',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='romance',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='taxi',
        ),
        migrations.AddField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(to='Reservation.service'),
        ),
    ]
