# Generated by Django 5.0.6 on 2024-06-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_remove_reservation_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationcode',
            name='expirationDate',
        ),
    ]
