# Generated by Django 5.0.6 on 2024-06-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0006_remove_confirmationcode_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='Reservation.service'),
        ),
    ]
